---
description: "#{repo}"
builds:
- platform: "debian"
  arch: "arm64"
  asset_filename: "#{repo}_#{version}_ruby-2.4.4_debian_linux_arm64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'arm64'"
  -  "entity.system.platform_family == 'debian'"
