name: Build Docker Image CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu20.04
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v2
    - name: select platform to test
      id: random_platform
      run: echo ::set-output name=PLATFORM::$(./build_scripts/random_test_platform.sh)    
    - name: Get the version
      id: get_version
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/') 
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: echo settings
      id: echo_settings
      run: "echo platform: ${{ steps.random_platform.outputs.PLATFORM }} version: ${{ steps.get_version.outputs.VERSION }}" 
    - uses: uraimo/run-on-arch-action@v2.1.1
      name: Build and test debian 
      #if: steps.get_version.outputs.VERSION || github.event_name == 'pull_request' || steps.random_platform.outputs.PLATFORM == 'debian' 
      with:
        arch: ${{ matrix.arch }}
        distro: ${{ matrix.distro }}
        githubToken: ${{ github.token }}
        env: |
          REPO_SLUG: ${{ github.repository }}  
        run: ./build_scripts/build_debian_platforms.sh
    - name: create checksum file
      run: ./checksum.sh 
    - name: Release tagged version
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/') 
      env: 
        TAG: ${{ steps.get_version.outputs.VERSION }}
        REPO_SLUG: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./upload.sh
